# -*- coding: utf-8 -*-
"""PotatoLeaf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lu2vi-4DAFW9dp4MY9rEo9E6sd5MU2cE
"""

# ==========================================
# POTATO LEAF DISEASE CLASSIFICATION
# Dataset: PLD (3 Classes)
# Target Accuracy: >90%
# ==========================================

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
from sklearn.metrics import confusion_matrix, classification_report

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers

import os
from google.colab import files

# --- STEP 1: KAGGLE SETUP (FIXED) ---
if not os.path.exists('/root/.kaggle/kaggle.json'):
    print("Please upload your kaggle.json file.")
    uploaded = files.upload()

    # Get the name of the uploaded file (handles 'kaggle (1).json' etc.)
    uploaded_file_name = list(uploaded.keys())[0]

    !mkdir -p ~/.kaggle
    # This line moves and renames whatever you uploaded to exactly 'kaggle.json'
    os.rename(uploaded_file_name, 'kaggle.json')
    !cp kaggle.json ~/.kaggle/
    !chmod 600 ~/.kaggle/kaggle.json
    print("Kaggle API key configured successfully!")

# --- STEP 2: DOWNLOAD & UNZIP ---
print("Downloading dataset...")
!kaggle datasets download -d rizwan123456789/potato-disease-leaf-datasetpld
!unzip -q potato-disease-leaf-datasetpld.zip -d potato_data

# --- STEP 3: PATH CONFIGURATION ---
# We check the directory to make sure we have the right path
base_dir = "/content/potato_data/PLD_3_Classes_256"
train_dir = os.path.join(base_dir, "Training")
val_dir = os.path.join(base_dir, "Validation")

# Load datasets
BATCH_SIZE = 32
IMAGE_SIZE = (224, 224)

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    val_dir,
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

class_names = train_ds.class_names
print(f"Detected classes: {class_names}")

# Count files per class
counts = [len(os.listdir(os.path.join(train_dir, name))) for name in class_names]

plt.figure(figsize=(15, 5))

# 1. Bar Chart
plt.subplot(1, 3, 1)
sns.barplot(x=class_names, y=counts, palette='viridis')
plt.title('Class Distribution (Bar)')

# 2. Pie Chart
plt.subplot(1, 3, 2)
plt.pie(counts, labels=class_names, autopct='%1.1f%%', colors=['#4CAF50', '#FF9800', '#F44336'])
plt.title('Class Distribution (Pie)')

# 3. Sample Images
plt.subplot(1, 3, 3)
for images, labels in train_ds.take(1):
    plt.imshow(images[0].numpy().astype("uint8"))
    plt.title(f"Label: {class_names[np.argmax(labels[0])]}")
    plt.axis("off")

plt.tight_layout()
plt.show()

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# --- 1. SETUP DATA AUGMENTATION ---
# This creates "variations" of your images so the model isn't tricked by angles
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.1),
])

# --- 2. SETUP BASE MODEL ---
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False

# --- 3. ASSEMBLE THE COMPLETE MODEL ---
model = models.Sequential([
    layers.Input(shape=(224, 224, 3)),   # Define the input layer
    data_augmentation,                  # <--- FIX 1: Augmentation (Training only)
    layers.Lambda(preprocess_input),     # <--- FIX 2: Normalization (Crucial!)
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),                 # Slightly higher dropout for better generalization
    layers.Dense(len(class_names), activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# --- STEP 6: TRAINING ---
print("\nStarting Training (Phase 1: Head Only)...")
history = model.fit(train_ds, validation_data=val_ds, epochs=5)

# Fine-tuning to reach >90% accuracy
print("\nStarting Fine-tuning (Phase 2: All Layers)...")
base_model.trainable = True
model.compile(optimizer=optimizers.Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])
history_fine = model.fit(train_ds, validation_data=val_ds, epochs=5)

# --- STEP 7: EVALUATION & PLOTS ---
# Combine histories
acc = history.history['accuracy'] + history_fine.history['accuracy']
val_acc = history.history['val_accuracy'] + history_fine.history['val_accuracy']
loss = history.history['loss'] + history_fine.history['loss']
val_loss = history.history['val_loss'] + history_fine.history['val_loss']

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(acc, label='Train Accuracy')
plt.plot(val_acc, label='Val Accuracy')
plt.title('Accuracy over Epochs')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(loss, label='Train Loss')
plt.plot(val_loss, label='Val Loss')
plt.title('Loss over Epochs')
plt.legend()
plt.show()

# --- STEP 8: CONFUSION MATRIX ---
print("\nGenerating Confusion Matrix...")
y_true, y_pred = [], []
for x, y in val_ds:
    y_true.extend(np.argmax(y.numpy(), axis=1))
    y_pred.extend(np.argmax(model.predict(x, verbose=0), axis=1))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

import math

# Define the number of images to show
num_images = 8
plt.figure(figsize=(20, 10))
plt.suptitle("Sample Predictions per Disease Class", fontsize=20)

# Take one batch from the validation dataset
for images, labels in val_ds.take(1):
    # Get predictions for the entire batch
    preds = model.predict(images, verbose=0)

    for i in range(num_images):
        plt.subplot(2, 4, i + 1)

        # Convert image for display
        img = images[i].numpy().astype("uint8")
        plt.imshow(img)

        # Get labels
        actual_label = class_names[np.argmax(labels[i])]
        predicted_label = class_names[np.argmax(preds[i])]
        confidence = np.max(preds[i]) * 100

        # Color green if correct, red if wrong
        color = 'green' if actual_label == predicted_label else 'red'

        plt.title(f"Actual: {actual_label}\nPred: {predicted_label} ({confidence:.1f}%)",
                  color=color, fontsize=12)
        plt.axis("off")

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

import pandas as pd
import tensorflow as tf
import numpy as np

# 1. Collect model data safely
layers_data = []
for layer in model.layers:
    # We use a try-except or check for output_shape
    try:
        out_shape = layer.output_shape
    except (AttributeError, RuntimeError):
        # Fallback for layers that don't have it initialized
        out_shape = "Multiple"

    layers_data.append({
        "Layer (type)": f"{layer.name} ({layer.__class__.__name__})",
        "Output Shape": str(out_shape),
        "Param #": f"{layer.count_params():,}"
    })

# 2. Create DataFrame
df_summary = pd.DataFrame(layers_data)

# 3. Add total calculations
total_params = model.count_params()
trainable_params = np.sum([tf.keras.backend.count_params(w) for w in model.trainable_weights])
non_trainable_params = total_params - trainable_params

# 4. Display totals
print(f"Total params: {total_params:,}")
print(f"Trainable params: {trainable_params:,}")
print(f"Non-trainable params: {non_trainable_params:,}")
print("-" * 30)

# 5. Display the table
# If you want it to look extra nice in Colab, use display()
from IPython.display import display
display(df_summary)

from google.colab import files
from tensorflow.keras.preprocessing import image

def test_final_prediction():
    print("--- Testing Updated Model ---")
    uploaded = files.upload()

    for fn in uploaded.keys():
        # 1. Load Image
        img = image.load_img(fn, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0) # (1, 224, 224, 3)

        # NOTE: We do NOT divide by 255 here anymore!
        # The model's Lambda layer handles it.

        # 2. Predict
        predictions = model.predict(img_array)

        # 3. Display
        plt.imshow(img)
        predicted_idx = np.argmax(predictions[0])
        confidence = np.max(predictions[0]) * 100

        plt.title(f"Result: {class_names[predicted_idx]}\nConfidence: {confidence:.2f}%")
        plt.axis('off')
        plt.show()

test_final_prediction()

# 1. Save the model to the Colab disk
model_name = 'potato_disease_model.h5'
model.save(model_name)
print(f"Model saved as {model_name}")

# 2. Save the class names (you will need these for your GUI!)
import json
with open('class_names.json', 'w') as f:
    json.dump(class_names, f)

# 3. Download the files to your local computer
from google.colab import files
files.download(model_name)
files.download('class_names.json')
